# name: Build and Release

# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Use Node.js 18
#         uses: actions/setup-node@v2
#         with:
#           node-version: 18

#       - uses: pnpm/action-setup@v2
#         with:
#           version: 6.0.2
#           run_install: |
#             - recursive: true
#               args: [--frozen-lockfile, --strict-peer-dependencies]
#             - args: [--global, gulp, prettier, typescript]

#       - name: Install dependencies and build
#         run: |
#           pnpm install
#           pnpm tauri build

#       - name: Upload DMG files as artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           name: Spotlit-dmg
#           path: ./src-tauri/target/release/bundle/dmg/**.**
